name: Translate Uploaded Files

on:
  issue_comment:
    types: [created, edited, deleted]

jobs:
  translate:
    runs-on: ubuntu-latest

    permissions:
      issues: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests polib openai

      - name: Extract and download files from issue body
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python .github/scripts/download_attachments.py ${{ github.event.issue.body }} ${{ github.event.issue.number }}

      - name: Translate files
        env:
          OPENAI_API_KEY: ${{ secrets.SILICON_API_KEY }}
        run: |
          python .github/scripts/translate_uploaded.py downloaded_files

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: translated-files
          path: downloaded_files/*.po

      - name: Comment on issue with result
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python .github/scripts/comment_result.py ${{ github.event.issue.number }}
