name: Translate PO files on Issue

on:
  issues:
    types: [opened]

jobs:
  translate:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      issues: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install polib openai

      - name: Run translation script
        env:
          OPENAI_API_KEY: ${{ secrets.SILICON_API_KEY }}
        run: |
          python translate.py

      - name: Commit translated files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add translations/
          git commit -m "Auto-translate on issue: #${{ github.event.issue.number }}" || echo "No changes"
          git push

      - name: Comment on issue
        run: |
          gh issue comment ${{ github.event.issue.number }} --body "✅ 自动翻译完成。所有 .po 文件已更新。"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
