name: Translate Uploaded PO Files

on:
  issues:
    types: [opened]

jobs:
  translate-uploaded:
    if: contains(github.event.issue.body, 'user-images.githubusercontent.com')
    runs-on: ubuntu-latest

    permissions:
      issues: write
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Create upload folder
        run: mkdir uploaded

      - name: Download attachments from issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python .github/scripts/download_attachments.py "${{ github.event.issue.number }}"

      - name: Translate PO files
        env:
          OPENAI_API_KEY: ${{ secrets.SILICON_API_KEY }}
        run: |
          python .github/scripts/translate_uploaded.py uploaded

      - name: Upload translated files as artifact
        uses: actions/upload-artifact@v3
        with:
          name: translated-po-files
          path: uploaded/*.po

      - name: Comment back
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh issue comment ${{ github.event.issue.number }} --body "Translate Complete"
