name: Translate Uploaded Files

on:
  issue_comment:
    types: [created, edited, deleted]

jobs:
  translate:
    runs-on: ubuntu-latest

    permissions:
      issues: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests polib openai

      - name: Extract and download files from issue body
        env:
          ISSUE_BODY: ${{ github.event.comment.body }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: |
          python .github/scripts/download_attachments.py

      - name: Translate files
        env:
          OPENAI_API_KEY: ${{ secrets.SILICON_API_KEY }}
        run: |
          python .github/scripts/translate_uploaded.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: translated-files
          path: downloaded_files/*.po